[package]
name = "ogg-shortener"
version = "0.1.0"
authors = ["Hossein Noroozpour (Thany Hulixer) <hossein.noroozpour@gmail.com>"]

[dependencies]
conrod = "*"
piston_window = "0.52"
find_folder = "*"
rand = "*"
vorbis = "*"
vorbis-sys = "*"
vorbisenc-sys = "*"
libc = "*"