[package]
name = "ogg-shortener"
version = "0.1.0"
authors = ["Hossein Noroozpour (Thany Hulixer) <hossein.noroozpour@gmail.com>"]

[dependencies]
gtk = { version = "*", features = ["v3_16"] }
vorbis = "*"
vorbis-sys = "*"
